#!/bin/bash 
#============================================================= 
# 
apt-get install anjuta --force-yes -y
apt-get install anjuta-common --force-yes -y
apt-get install apache --force-yes -y
apt-get install at-spi-doc              --force-yes -y
apt-get install autobook                --force-yes -y
apt-get install autoconf                --force-yes -y
apt-get install autoconf2.13            --force-yes -y
apt-get install autoconf-archive        --force-yes -y
apt-get install autogen                 --force-yes -y
apt-get install automake                --force-yes -y
apt-get install bison                   --force-yes -y
apt-get install ctags                   --force-yes -y
apt-get install cvs                     --force-yes -y
apt-get install devhelp                 --force-yes -y
apt-get install devhelp-books           --force-yes -y
apt-get install exuberant-ctags         --force-yes -y
apt-get install flex                    --force-yes -y
apt-get install g++ 										--force-yes -y
apt-get install g77                     --force-yes -y
apt-get install gcc                     --force-yes -y
apt-get install gcj                     --force-yes -y
apt-get install gda2-freetds            --force-yes -y
apt-get install gda2-mysql              --force-yes -y
apt-get install gda2-odbc               --force-yes -y
apt-get install gda2-postgres           --force-yes -y
apt-get install gda2-sqlite             --force-yes -y
apt-get install glade-2                 --force-yes -y
apt-get install glade-doc-2             --force-yes -y
apt-get install glade-gnome-2           --force-yes -y
apt-get install gnome-devel             --force-yes -y
apt-get install gnu-standards           --force-yes -y
apt-get install gnutls-bin              --force-yes -y
apt-get install httpd                   --force-yes -y
apt-get install indent 									--force-yes -y
apt-get install libcompress-zlib-perl   --force-yes -y
apt-get install libgail-doc             --force-yes -y
apt-get install libglib2.0-doc          --force-yes -y
apt-get install libgnome2-dev           --force-yes -y
apt-get install libgnome2-doc           --force-yes -y
apt-get install libgnomecanvas2-doc     --force-yes -y
apt-get install libgnomemm2.0-dev       --force-yes -y
apt-get install libgnomeui-doc          --force-yes -y
apt-get install libgtk2.0-dev           --force-yes -y
apt-get install libgtk2.0-doc           --force-yes -y
apt-get install libgtkmm2.0-dev         --force-yes -y
apt-get install libgtkmm2.0-doc         --force-yes -y
apt-get install libhtml-format-perl     --force-yes -y
apt-get install libio-socket-ssl-perl   --force-yes -y
apt-get install libltdl3-dev            --force-yes -y
apt-get install libmailtools-perl 			--force-yes -y
apt-get install libpango1.0-doc         --force-yes -y
apt-get install libpcre3                --force-yes -y
apt-get install libstdc++5-3.3-doc      --force-yes -y
apt-get install libtool                 --force-yes -y
apt-get install libtool-doc             --force-yes -y
apt-get install manpages-dev            --force-yes -y
apt-get install menu                    --force-yes -y
apt-get install orbit2                  --force-yes -y
apt-get install stl-manual              --force-yes -y
apt-get install shared-mime-info        --force-yes -y
apt-get install ttf-thryomanes          --force-yes -y